<?php

/**
* Implementation of hook_permission().
*/
function mysearch_permission() {
 return array(
   'access mysearch' => array(
       'title' => 'Access My Search',
       'description' => 'Allows a user to access search results',
     )
   );
}


/**
* Implementation of hook_menu().
*/
function mysearch_menu() {
 $items['mysearch/%'] = array(
   'title' => 'Search',
   'title callback' => 'mysearch_title',
   'title arguments' => array(1),
   'page callback' => 'mysearch_searchpage',
   'page arguments' => array(1),
   'access arguments' => array('access mysearch'),
   'type' => MENU_SUGGESTED_ITEM,
 );
 return $items;
}


/**
* Menu callback provides a simple list of nodes matching the
* search term Example: hitting the URL: 
*   http://domain.com/mysearch/example
* will return a list of links to nodes which have the word
* example in them.
*/
function mysearch_searchpage($searchterm) {

 $query = db_select('node' , 'n');
 $query
    ->condition('title', '%'.$searchterm.'%', 'LIKE')
    ->fields('n', array('nid', 'title'));
    
 $get_node_result = $query->execute();

 $search_results = "<ul>";
 
 foreach($get_node_result as $node) {
    $search_results .= '<li>'.l($node->title, 
                                drupal_get_path_alias('node/'.$node->nid), 
                                    array('attributes' => array(
                                        'title' => $node->title))).'</li>';
 }
 $search_results  .= '</ul>';
 return $search_results;
}

/**
*   Return page title
*/

function mysearch_title($arg){
    return t('Search for @arg', array('@arg' => $arg));
}
